# Generated by Django 4.2.5 on 2023-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название часов')),
                ('description', models.TextField(verbose_name='Укажите описание часов')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Добавьте фото')),
                ('made_in', models.TextField(verbose_name='Производитель')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('watches_author', models.TextField(verbose_name='Укажите создателя часов')),
                ('operating_principle', models.TextField(choices=[('механические', 'механические'), ('электронные', 'электронные'), ('кварцевые', 'кварцевые')], verbose_name='Укажите принцип работы часов')),
                ('characteristics', models.TextField(choices=[('обычный', 'обычный'), ('водонепроницаемый', 'водонепроницаемый')], verbose_name='Укажите характеристику часов')),
                ('data_of_made', models.PositiveIntegerField(verbose_name='Укажите год производства')),
                ('video_of_watches', models.URLField(verbose_name='Укажите ссылку на видео часов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
