# Generated by Django 4.2.5 on 2023-09-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='characteristics',
            field=models.CharField(choices=[('обычный', 'обычный'), ('водонепроницаемый', 'водонепроницаемый')], max_length=100, null=True, verbose_name='Укажите характеристику часов'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='operating_principle',
            field=models.CharField(choices=[('механические', 'механические'), ('электронные', 'электронные'), ('кварцевые', 'кварцевые')], max_length=100, null=True, verbose_name='Укажите принцип работы часов'),
        ),
    ]
