# Generated by Django 4.2.5 on 2023-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0003_alter_watches_options_alter_watches_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='watches',
            name='data_of_made',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите год производства'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Добавьте фото'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='made_in',
            field=models.TextField(null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите название часов'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='video_of_watches',
            field=models.URLField(null=True, verbose_name='Укажите ссылку на видео часов'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='watches_author',
            field=models.TextField(null=True, verbose_name='Укажите создателя часов'),
        ),
    ]
