# Generated by Django 4.2.5 on 2023-10-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0005_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
